### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by David-Kr** [Ceskasporitelna/cs-locker-ui-sdk-droid#11]
All kind of devices
154 Crashes from Locker
java.lang.RuntimeException: Unable to start activity ComponentInfo
{cz.csas.georgego/cz.csas.lockerui.MainActivity}
: cz.csas.cscore.error.CsLockerError: You are already registered.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
at android.app.ActivityThread.access$800(ActivityThread.java:145)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5137)
at java.lang.reflect.Method.invokeNative(Method.java)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: cz.csas.cscore.error.CsLockerError: You are already registered.
at cz.csas.cscore.locker.LockerImpl.register(LockerImpl.java:93)
at cz.csas.lockerui.LockerUIFragment.onClick(LockerUIFragment.java:159)
at cz.csas.lockerui.LockerUIFragment.init(LockerUIFragment.java:108)
at cz.csas.lockerui.LockerUIFragment.populateViewForOrientation(LockerUIFragment.java:79)
at cz.csas.lockerui.LockerUIFragment.onCreateView(LockerUIFragment.java:66)
at android.app.Fragment.performCreateView(Fragment.java:1700)
at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:890)
at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1062)
at android.app.BackStackRecord.run(BackStackRecord.java:684)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1447)
at android.app.Activity.performStart(Activity.java:5240)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
... 11 more

8786

**Comment by hauseja3** [comment]
This issue is probably caused by some kind of race condition and it was temporarily solved by using `trycatch` blok above `register` method (`startAuthenticationFlow` method in `LockerUI` respectively). 

It will be object of deeper analysis.

**Comment by bbindreiter** [comment]
we have added the try/catch block into george go for now
