### ISSUE TITLE
AuthFlowOptions error 

### ISSUE THREAD

**Issue by hauseja3** [Ceskasporitelna/cs-locker-ui-sdk-droid#16]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.csas.app.mujstav/cz.csas.lockerui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cz.csas.lockerui.config.AuthFlowOptions.getLockedScreenText()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
       at android.app.ActivityThread.access$900(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:234)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Vratislav** [comment]
Library versions:

implementation 'cz.csas:cs-core-sdk:1.5.1@aar'
implementation 'cz.csas:cs-locker-ui-sdk:3.1.0@aar'

**Comment by hauseja3** [comment]
AuthFlowOptions passed to SDK as null. Prevention was implemented in new version, used defaults to prevent null pointer exception.
