### ISSUE TITLE
crash pri pouziti gesta

### ISSUE THREAD

**Issue by kvarackova** [Ceskasporitelna/cs-locker-ui-sdk-droid#19]
Ahoj.

Na appke Friends 24, ktora pouziva locker libku sa snazim povysit verzie:
- cs-core-sdk z 1.3.3 na 1.5.1
- cs-locker-ui-sdk z 2.0.3 na 3.1.2

Appku so starsimi verziami libiek mam zabezpecenu gestom. Appku updatnem na veriu, ktora pouziva nove verzie libiek, ale po zadani spravneho gesta appka crashne nasledovne:

```
05-11 13:34:27.200 8545-8545/cz.csas.app.friends24.fresh I/CS_LOG: [Locker UNLOCKED] Unlock by GESTURE was succesful.
05-11 13:34:27.201 8545-8661/cz.csas.app.friends24.fresh E/AndroidRuntime: FATAL EXCEPTION: BackgroundThread
    Process: cz.csas.app.friends24.fresh, PID: 8545
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at cz.csas.cscore.client.crypto.CryptoManagerImpl.createOfflineGesturePasswordWithCollision(CryptoManagerImpl.java:261)
        at cz.csas.cscore.client.crypto.CryptoManagerImpl.createOfflinePasswordWithCollision(CryptoManagerImpl.java:205)
        at cz.csas.cscore.storage.KeychainManagerImpl.storeOfflinePasswordHash(KeychainManagerImpl.java:241)
        at cz.csas.cscore.locker.LockerImpl$9.run(LockerImpl.java:629)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

Myslim, ze problem bude s tym, ze sa menilo gesto z gridu MxM na grid MxN.
Z `lockTypes.add(new GestureLock(3,4)); `na `lockTypes.add(new GestureLock(new GestureGridSize(3, 3), 4));`

Mohol by sa na to, niekto, prosim mrknut?

**Comment by kirscfil** [comment]
@kvarackova Zdravím, podíváme se na zpětnou kompatibilitu obou verzí a dáme vědět, co s tím.

**Comment by hauseja3** [comment]
@kvarackova on it, sorry, mám s tím trochu zpoždění.
