### ISSUE TITLE
Null Pointer crashe

### ISSUE THREAD

**Issue by kvarackova** [Ceskasporitelna/cs-locker-ui-sdk-droid#20]
Zdravim.

V Crashlyticse sa nam objavuju nejake crashe, mrknete sa na to, prosim?

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {cz.csas.app.mujstav/cz.csas.lockerui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3749)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3789)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:6733)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at android.view.LayoutInflater.from(LayoutInflater.java:229)
       at cz.csas.lockerui.ResultFragment$1.run(SourceFile:98)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6703)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
	   
	   
	   
Fatal Exception: java.lang.NullPointerException
       at cz.csas.lockerui.LockerUIFragment.a(SourceFile:122)
       at cz.csas.lockerui.LockerUIFragment.a(SourceFile:106)
       at cz.csas.lockerui.LockerUIFragment.a(SourceFile:81)
       at cz.csas.lockerui.LockerUIFragment.onCreateView(SourceFile:68)
       at android.app.Fragment.performCreateView(Fragment.java:1700)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
       at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:781)
       at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1496)
       at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:495)
       at cz.csas.lockerui.MainActivity.onBackPressed(SourceFile:407)
       at android.app.Activity.onKeyUp(Activity.java:2219)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2703)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2456)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(SourceFile:534)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(SourceFile:58)
       at android.support.v7.app.b$b.dispatchKeyEvent(SourceFile:316)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2006)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4448)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4408)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3962)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4012)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3981)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4088)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3989)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4145)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3962)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4012)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3981)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3989)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3962)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4012)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3981)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4121)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4290)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2078)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1755)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1746)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2055)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5305)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by kvarackova** [comment]
Este jedna

Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at cz.csas.cscore.utils.Base64.encode(SourceFile:473)
       at cz.csas.cscore.client.crypto.CryptoManagerImpl.encodeBase64(SourceFile:129)
       at cz.csas.cscore.storage.KeychainManagerImpl.encryptToKeychain(SourceFile:373)
       at cz.csas.cscore.storage.KeychainManagerImpl.storeAccessToken(SourceFile:101)
       at cz.csas.cscore.CoreSDKImpl$1.success(SourceFile:181)
       at cz.csas.cscore.CoreSDKImpl$1.success(SourceFile:172)
       at cz.csas.cscore.client.rest.CallbackRunnable$1.run(SourceFile:43)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5659)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by hauseja3** [comment]
@kvarackova poslední null pointer je z CoreSDK, opravíme tedy tam.

**Comment by hauseja3** [comment]
Tracking here: https://github.com/Ceskasporitelna/cs-core-sdk-droid/issues/17
