### ISSUE TITLE
Nullpointer na vybraných zařízeních

### ISSUE THREAD

**Issue by rtippl-p** [Ceskasporitelna/cs-locker-ui-sdk-droid#26]
Ahoj,

zdá se, výrobci některých nových zařízení bez čtečky otisků prstů odstranili fingerprint service z jejich verze Androidu přestože jsou telefony na nových verzích systému. (7, 8)
Při pokusu o získání service `getActivity().getSystemService(Context.FINGERPRINT_SERVICE);` se tedy vrátí null a následný check na `FingerprintManager.isHardwareDetected()` hodí nullpointer.

Stacktrace lockeru:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
       at cz.csas.lockerui.RegisterFragment.checkFingerprintAvailability(RegisterFragment.java:213)
       at cz.csas.lockerui.RegisterFragment.setLockTypes(RegisterFragment.java:179)
       at cz.csas.lockerui.RegisterFragment.init(RegisterFragment.java:124)
       at cz.csas.lockerui.RegisterFragment.populateViewForOrientation(RegisterFragment.java:93)
       at cz.csas.lockerui.RegisterFragment.onCreateView(RegisterFragment.java:80)
       at android.app.Fragment.performCreateView(Fragment.java:2611)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1276)
       at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2421)
       at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
       at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055)
       at android.app.FragmentController.execPendingActions(FragmentController.java:403)
       at android.app.Activity.performStart(Activity.java:7199)
       at android.app.Activity.performRestart(Activity.java:7340)
       at android.app.Activity.performResume(Activity.java:7353)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by hauseja3** [comment]
@rtippl-p Ahoj, 

omlouvám se za zpoždění, odbavím to ještě dnes a vydám novou verzi.

**Comment by hauseja3** [comment]
v3.1.6 released.
